### ISSUE TITLE
Unable to install in 2.8 release

### ISSUE THREAD

**Issue by Scheherazade** [ScottishCyclops/tensionmap#10]
When I try to install the latest version of the addon in the 2.80 release, it comes up with an error message. I followed the install instructions, am I doing something wrong?

Thanks for maintaining this addon.

**Comment by twinkelmann** [comment]
Hey,

I just tested the latest version of tensionmap ([2.1.0](https://github.com/ScottishCyclops/tensionmap/releases/tag/2.1.0)) with Blender 2.8 final release (July 30) on Ubuntu 19.04.

It all works fine for me.
Can you list your operating system, Blender version, addon version, and copy the error message you are seeing ? A screenshot is fine if you can't copy the text.

Thanks in advance.

**Comment by Scheherazade** [comment]
Hi,

I'm on macOS High Sierra, latest version of tensionmap, July 30th Blender 2.80 release. Here's the error I get:

`Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/startup/bl_operators/userpref.py", line 643, in execute
    module_filesystem_remove(path_addons, os.path.basename(pyfile))
  File "/Applications/Blender.app/Contents/Resources/2.80/scripts/startup/bl_operators/userpref.py", line 48, in module_filesystem_remove
    os.rmdir(f_full)
OSError: [Errno 66] Directory not empty: '/Users/NEEB/Library/Application Support/Blender/2.80/scripts/addons/tensionmap'`

**Comment by twinkelmann** [comment]
This error happens when exactly ? On enabling ? On installing ? Looks like it is trying to delete a "tensionmap" folder in your addons, but this addon doesn't include a folder anymore. it's just "tensionmap.py".

Try deleting `/Users/NEEB/Library/Application Support/Blender/2.80/scripts/addons/tensionmap` manually, then re-installing the addon.

**Comment by Scheherazade** [comment]
Okay, I removed the old one that was installed and tried installing again and that seems to have done the trick. Thanks so much for the help.
