### ISSUE TITLE
Blender crashes when trying to render

### ISSUE THREAD

**Issue by riemenrille** [ScottishCyclops/tensionmap#17]
Hi,

I have tried several belnder builds but I have the same problem in all of them:
Blender crashes instantly as soon as I hit render.
I used the addon just the way it is described in the readme (attribute node with rgb split and then two normal maps).

Am I just doing something wrong or is there a bug?

thanks a lot for your work!

**Comment by riemenrille** [comment]
Ok, never mind. I have shape keys in my model so I guess thats causing the crashes. 
Could you pleeeaaaase integrade shape keys?  <3

**Comment by VincentKueszter** [comment]
There is a pull request that integrates shape keys.
Maybe you can try and see if that works?

**Comment by riemenrille** [comment]
Thanks,
I tried it but blender still crashes.

**Comment by ScottishCyclops** [comment]
> Ok, never mind. I have shape keys in my model so I guess thats causing the crashes.
> Could you pleeeaaaase integrade shape keys? <3

Shape keys are not supported for deformation, but they should not lead to a crash.

I haven't been able to reproduce the bug on: (Help > Save System Info)
```
version: 2.81 (sub 16), branch: master, commit date: 2019-12-04 11:32, hash: f1aa4d18d49d, type: Release
build date: 2019-12-04, 13:48:07
platform: Linux
```
Tried with/without shape keys, vertex colors & vertex groups, Evee & Cycles

Can you give me more insights on what your setup is ? OS, Version.
Can you make the simplest scene possible with Tension Map and test if the render crashes again ? It might be something to do with your scene specifically. 

Scott

**Comment by riemenrille** [comment]
Thank you for your effort. I ran the project on different systems and came to the conclusion that it might be a memory issue.

**Comment by ScottishCyclops** [comment]
Okay. Glad to hear you found a workaround.
I'll close this issue. Feel free to open a new one in case of problem.

Scott
