### ISSUE TITLE
Tension group naming confusion?

### ISSUE THREAD

**Issue by buzzkirill** [ScottishCyclops/tensionmap#2]
Hi, thanks for the awesome addon. Do you have a donation page set up? (sorry if this isn't the place to ask - I'm new to this place, this is my first comment ever)
It seems that the tension groups' names are reversed - the one that's called "stretch" actually marks areas that are squashed, and vice versa. Tested it on a blank new Blender file with a monkey head.

**Comment by ScottishCyclops** [comment]
Thanks a lot for reporting this mistake.

It was indeed inverted. I must say the source code I rewrote was a bit misleading.
I renamed some variables and changed some comments so it actually tells the truth.

Please download version `1.0.2` (Patch for #2 & #3).
I will mark this issue resolved, please open a new one if there is anything else.

As for your question about donations, I can always accept cryptocurrency, but not much else is "set up" right now. Paypal is a mess for donations.
Here are my Zcash addresses in case. Thanks a lot anyways <3

`ADDRESS REMOVED`
