### ISSUE TITLE
tm_tension Vertex Color not updating

### ISSUE THREAD

**Issue by ivanebeoulve** [ScottishCyclops/tensionmap#3]
hey, 

first of all thanks for continuing the work on this add-on.
I seem to have a problem getting it to work, the vertex color tm_tension just doesnt update when activating the plugin and the Update tension map shows up a bunch of errors each time I click it.
I'm using 2.79

![bug](https://user-images.githubusercontent.com/1312595/40455780-409e5238-5ea3-11e8-8512-50bc512c0f08.jpg)

**Comment by ScottishCyclops** [comment]
Thanks a lot for reporting this. I suppose the way colors are handled changed not so long ago in Blender.
Now it is not an object with "r, g, b, a" components, it is a list indexed with 0, 1, 2, 3.

Please download version `1.0.2` (Patch for #2 & #3) which fixes the error.
I will mark this issue resolved, please open a new one if there is anything else.
